name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04 # Python 3.6 isn't available on ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install black
          pip install ruff
          pip install -r requirements.txt
      - name: Lint with ruff
        run: |
          ruff .
      - name: Lint with black
        run: |
          black . --check
      - name: Test with pytest
        run: |
          pytest -v
